<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_courses extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id_courses' => array(
				'type' => 'INT',
				'constraint' => 0,
			),
			'name' => array(
				'type' => 'VARCHAR',
				'constraint' => 255,
			),
			'code' => array(
				'type' => 'VARCHAR',
				'constraint' => 4,
			),
		));

		$this->dbforge->add_key('id_courses', TRUE);

		$this->dbforge->create_table('courses', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('courses');
	}
}