<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_students extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id_students' => array(
				'type' => 'INT',
				'constraint' => 0,
			),
			'rut' => array(
				'type' => 'VARCHAR',
				'constraint' => 12,
			),
			'name' => array(
				'type' => 'VARCHAR',
				'constraint' => 255,
			),
			'lastName' => array(
				'type' => 'VARCHAR',
				'constraint' => 255,
			),
			'age' => array(
				'type' => 'INT',
				'constraint' => 0,
			),
			'id_courses' => array(
				'type' => 'INT',
				'constraint' => 0,
			),
		));

		$this->dbforge->add_key('id_students', TRUE);

		$this->dbforge->create_table('students', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('students');
	}
}