<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Students extends ORM {

	public $primary_key = 'id_students';
	public $foreign_key = array('\\Model\\Courses' => 'id_courses');

	function _init(){

		// Relationship definition
        self::$relationships = array(
                'course' => ORM::belongs_to('\\Model\\Courses'),
        );

        // Fields definition
		self::$fields = array(
			'id_students' => ORM::field('auto'),
			'rut' => ORM::field('char[12]'),
			'name' => ORM::field('char[255]'),
			'lastName' => ORM::field('char[255]'),
			'age' => ORM::field('int'),
			'id_courses' => ORM::field('int'),
		);

	}
}